name: Update Badges from Credly

# Controls when the action will run. 
on:
  workflow_dispatch:         # Able to manually run this workflow from the "Actions" tab
  schedule:
    - cron: "0 16 * * *"     # Runs at midnight Singapore time: (00:00 SGT, which is 16:00 UTC)
  pull_request:              # Triggered on pull requests

# Jobs to be executed
jobs:
  update-readme:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest   # The runner environment

    steps:
      # Checkout the repository to the runner
      - name: Checkout Code
        uses: actions/checkout@v2

      # Update README with the latest badges from Credly
      - name: Update README with Badges from Credly
        uses: pemtajo/badge-readme@2.4.0
        with:
          GH_TOKEN: ${{ secrets.CREDLY_BADGES_GH_TOKEN }}           # Secret GitHub Token for authentication
          COMMIT_MESSAGE: "Update README with latest Credly Badges" # Commit message when the README is updated
          CREDLY_USER: thehansong                                   # Credly user name
          CREDLY_SORT: RECENT                                       # Sort badges based on Recency
          BADGE_SIZE: 220                                            # Badge width, height
          NUMBER_LAST_BADGES: 10                                    # Show only the 10 most recently earned badges          
